server:
  port: 9006
  servlet:
    context-path: /bs

spring:
  mvc:
    #    servlet:
    #      load-on-startup: 1
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: bs #服务名称
  thymeleaf:
    # 禁用缓存
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        #连接池最大连接数（负值表示没有限制）默认8
        max-active: 100
        #连接池中最大空闲连接 默认8
        max-idle: 10
        #连接池中最小空闲连接 默认0
        min-idle: 3
  datasource:
    druid:
      portal:
        #   数据源基本配置
        url: jdbc:mysql://127.0.0.1:3306/management?allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root@123456
        #       数据源其他配置
        # 初始化连接数
        initialSize: 1
        # 连接池最小空闲
        minIdle: 1
        # 连接池最大使用连接数量
        maxActive: 20
        # 获取连接最大等待时间
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #   如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        #   合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapping/*/*.xml

#pagehelper分页插件 https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

logging:
  file:
    # 指定日志生成位置
    path: ../logs/bs
  level:
    root: info
    cn.net.ssd.mapper: debug

#自定义rsa加密文件生成地址
rsa:
  key:
    pubKeyFile: D:\auth_key\id_key_rsa.pub
    priKeyFile: D:\auth_key\id_key_rsa


# 雪花算法机器ID（0〜1023）
snowflake:
  workerId: 333

knife4j:
  # 开启增强
  enable: true
  # 开启登录认证
  basic:
    enable: true
    username: admin
    password: 123456
  #是否为生产环境进行拒绝访问；true为关闭knife4j页面访问功能
  production: false

ssd:
  # 没有完全绕过spring允许匿名访问的url，没有完全绕过spring security。
  permitUrls:
    - '/'
    - '/common/**'
    - '/loginerror'
    - '/authException'
    - '/error'
    - '/sessionInvalid'
    - '/sensitive/excelUpload'
    - '/thesaurus/excelUpload'
  # WebSecurity 不拦截的url，完全绕过spring security。主要配置一些静态资源
  ignoreUrls:
    - '/login/token'
    - '/druid/**'
    - '/favicon.ico'
    - '/assets/**'
    - '/bootstrap/**'
    - '/css/**'
    - '/js/**'
    - '/image/**'
    - '/plugin/**'
    - '/webjars/**'
    - '/swagger-ui.html'
    - '/v2/**'
    - '/v3/**'
    - '/img.icons/**'
    - '/swagger-ui/**'
    - '/swagger-resources/**'
    - '/doc.html'
  checkTokenUrls:
    - '/userManage/**'