package cn.net.ssd.common.util;


import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class Constants {

    public static final ThreadPoolExecutor earlyValidationThreadPool = new ThreadPoolExecutor(5, 10,
            200, TimeUnit.SECONDS, new ArrayBlockingQueue<Runnable>(5),
            Executors.defaultThreadFactory(), new ThreadPoolExecutor.CallerRunsPolicy());
    
    
    public static final Set<String> repeatPunctuationSet= new HashSet<String>(){{
        add("，，");
        add("；；");
        add("。。");
        add("，。");
        add("，！");
        add("，、");
        add("，~");
        add("，-");
        add("，）");
        add("，%");
        add("，；");
        add("，：");
        add("。，");
        add("。！");
        add("。、");
        add("。~");
        add("。-");
        add("。%");
        add("。；");
        add("。：");
        add("！，");
        add("！。");
        add("！！");
        add("！、");
        add("！~");
        add("！-");
        add("！%");
        add("！；");
        add("！：");
        add("、，");
        add("、。");
        add("、！");
        add("、、");
        add("、~");
        add("、-");
        add("、）");
        add("、%");
        add("、；");
        add("、：");
        add("~，");
        add("~。");
        add("~！");
        add("~、");
        add("~~");
        add("~（");
        add("~）");
        add("~%");
        add("~；");
        add("~：");
        add("~“");
        add("~”");
        add("~‘");
        add("~’");
        add("-，");
        add("-。");
        add("-！");
        add("-、");
        add("-~");
        add("--");
        add("-（");
        add("-）");
        add("-%");
        add("-；");
        add("-：");
        add("-“");
        add("-”");
        add("-‘");
        add("-’");
        add("（，");
        add("（。");
        add("（！");
        add("（、");
        add("（~");
        add("（-");
        add("（）");
        add("（%");
        add("（；");
        add("（：");
        add("（”");
        add("（’");
        add("）（");
        add("）%");
        add("%%");
        add("%“");
        add("%‘");
        add("：，");
        add("：。");
        add("：！");
        add("：、");
        add("：~");
        add("：-");
        add("：）");
        add("：%");
        add("：：");
        add("：；");
        add("：”");
        add("：’");
        add("；，");
        add("；。");
        add("；！");
        add("；、");
        add("；~");
        add("；-");
        add("；）");
        add("；%");
        add("；；");
        add("；：");
        add("；”");
        add("；’");
        add("“，");
        add("“。");
        add("“、");
        add("“~");
        add("“-");
        add("“)");
        add("“%");
        add("“；");
        add("“：");
        add("““");
        add("“”");
        add("“’");
        add("”%");
        add("”“");
        add("””");
        add("”‘");
        add("‘，");
        add("‘。");
        add("‘！");
        add("‘、");
        add("‘~");
        add("‘-");
        add("‘）");
        add("‘%");
        add("‘；");
        add("‘：");
        add("‘”");
        add("‘‘");
        add("‘’");
        add("’%");
        add("’“");
        add("’‘");
        add("’’");
    }};
    public static final Set<String> irrationalPunctuationSet= new HashSet<String>(){{
        add("？");
        add("?");
    }};
    public static final Set<String> enPunctuationSet= new HashSet<String>(){{
        add("!");
        add(":");
        add("\"");
    }};
}